#!/bin/bash
set -e

staged_go_files=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$' || true)

if [ -z "$staged_go_files" ]; then
  exit 0
fi

echo "Formatting staged Go files..."
go tool golangci-lint fmt $staged_go_files
git add $staged_go_files
echo "Done"

echo "Running linter..."
go tool golangci-lint run --new-from-rev=HEAD~1 --fix
git add $staged_go_files
echo "Done"
