version: "2"
linters:
  settings:
    errcheck:
      check-blank: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
      - linters:
          - errcheck
        source: "cmd\\.Flags\\(\\)\\."
      - linters:
          - errcheck
        source: "fmt\\.Fscan\\("
      - linters:
          - staticcheck
        text: "ST1005"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
