version: 2

builds:
  - main: .
    binary: dotmem
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.buildTime={{.Date}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz

checksum:
  name_template: checksums.txt

release:
  draft: false
